### ISSUE TITLE
large file print to serial?

### ISSUE THREAD

**Issue by jshep321** [thebigpotatoe/Effortless-SPIFFS#11]
When trying to open a file and dump the contents to the Serial output, a crash occurs if the filesize is too large.  In my case it was about 6kB.  Running on an ESP32 in Arduino framework.

Function snippet that broke:
```
  fileSystem.openFromFile(filename, payload);
  Serial.print("File contents: \n");  Serial.println(payload);  

```

Since I'm still in development, I dump my file to the Serial port at every boot.  Once the file grew too large, I got stuck in a reboot/crash loop until I wiped the filesystem.

I *think* I had plenty of heap available (but my heap debug prints were off), but still hit this wall.

Any way to open a SPIFFS file as a stream instead of a String, etc.?

**Comment by thebigpotatoe** [comment]
| Any way to open a SPIFFS file as a stream instead of a String, etc.?

Not at this stage, however that is a great suggestion for larger files. Only caveat is development is harder than opening a file into some buffer variable which is probably why I didn't do it in the first place. 

| In my case it was about 6kB. Running on an ESP32 in Arduino framework.

I vaguely remember there being an issue with the ESP32 and large spiffs files mentioned in one or two other libraries. I cannot remember the specifics, but maybe if you can write some tests for your use case to dig a little further to understand the issue. Maybe something like incrementally increase the file size and open it while monitoring the heap?

**Comment by jshep321** [comment]
OK thanks.  I assumed this would eventually be a problem, but I was surprised I ran into this with such a small file.  I'll look into other options for streams, etc in the future.

Will do the debugging steps in the next week or so... Will report back!

**Comment by thebigpotatoe** [comment]
Closing due to stale. If needed, please reopen
