### ISSUE TITLE
fileSystem.saveToFile("somefile.txt", "21342314") not saving file

### ISSUE THREAD

**Issue by KiavashS** [thebigpotatoe/Effortless-SPIFFS#2]
Hello,

I'm trying to use this tool to store values such as MQTT server address in my ESP8266 Wemos D1 Mni. But when I run the **fileSystem.saveToFile("somefile.txt", "21342314")**, it always returns Fale.

I've tried to send a String, char, char*, etc and it's all the same result. False. So I tried manually writing the string as per the above example and it also just returns False and no the it's stored (I think).

Any idea what's happening?

When I try to safe String or bool values, I also get these compilation errors:
- no matching function for call to 'eSPIFFS::saveToFile(const char [12], bool)'
- no matching function for call to 'eSPIFFS::saveToFile(const char [12], String)'

I'm a noob C++ coder. So I wouldn't be surprised if I'm doing something obvious wrong. I'd appreciate if you could point out my mistake if you see any.

thanks

**Comment by thebigpotatoe** [comment]
A couple of things may be wrong here, lets hope its a easy case.

First off, make sure you have a SPIFFS size selected from the tools menu in the Arduino IDE (or your IDE). I have no idea how many times I have not selected this and spent hours trying to figure it out.

If that is ok, then I suggest uploading the example and seeing if that will compile first, then just see how it runs. The example should be fully working straight out of the box, so if that is returning false, there may be another issue. 

If tha'ts the case try manually use an ESP8266 core SPIFFS example to probe your flash chip. Maybe there is something wrong with it?

As for your compilation question, I assume safe string is the inbuilt Arduino string? Because that should be supported by the code for sure, so I'm not 100% on why you would be getting those errors about unless you have imported it incorrectly or there are other errors in your code causing that issue to pop up.

None the less, try the steps above and let me know how you go.

**Comment by KiavashS** [comment]
OMG!! Select a SPIFFS size! That was my problem. Not being able to work that out lead me down some other troubleshooting that made it even worst with those compile errors. Nevermind them.

This is a great tool that just works (if the user isn't making mistakes of their own).

**Comment by thebigpotatoe** [comment]
Haha, no worries. Glad I could possibly save you some time. I cannot tell you how many times I've done it.

Any other issues or queries, feel free to post.
